version: '3'
services:
  tracker:
    container_name: tracker
    image: giansz/tracker:latest
    ports:
      - "5000:5000"
    environment:
      - TRACKER_IP=172.20.0.6
      - TRACKER_PORT=5000
    networks:
      mynet:
        ipv4_address: 172.20.0.6
networks:
  mynet:
    external:
      name: mynet